name: Trigger Regression Tests

on:
  workflow_dispatch:

name: First Workflow

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Do initial setup
        run: echo "Initial setup complete"

      - name: Trigger Second Workflow
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo "Triggering the second workflow..."
          curl -X POST -H "Authorization: token $GH_TOKEN" \
               -H "Accept: application/vnd.github.everest-preview+json" \
               https://api.github.com/repos/${{ github.repository }}/dispatches \
               -d '{"event_type":"start_regression_tests","client_payload":{"run_id":"${{ github.run_id }}"}}'
          echo "Second workflow triggered successfully."

  wait_for_feedback:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Wait for feedback
        run: echo "Waiting for feedback from the second workflow..."

      - name: Process feedback
        run: |
          echo "Feedback received: ${{ github.event.client_payload.status }}"
          if [ "${{ github.event.client_payload.status }}" != "success" ]; then
            echo "Second workflow failed!"
            exit 1
          fi
          echo "Second workflow succeeded!"
